server {
    listen 80;
    server_name _;

    # CTFd Main Platform
    location / {
        proxy_pass http://ctfd:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Web Challenge Level
    location /web-lvl/ {
        proxy_pass http://web-lvl:80/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # AI Challenge Level
    location /ai-lvl/ {
        proxy_pass http://ai-lvl:5021/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Custom System Challenge Level (Web Terminal & Netcat proxy)
    location /custom/ {
        proxy_pass http://custom-system:31337/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}